FROM --platform=linux/amd64 envoyproxy/envoy-dev:latest

COPY ./envoy-https-passthrough.yaml /etc/envoy.yaml
COPY ./envoy-wasm/main.wasm /etc/main.wasm
RUN chmod go+r /etc/envoy.yaml
RUN touch /etc/access.log && chmod go+wr /etc/access.log
CMD ["/usr/local/bin/envoy", "-c /etc/envoy.yaml", "--log-level trace"]
