FROM --platform=linux/amd64 envoyproxy/envoy:v1.22-latest

COPY ./brotli-envoy.yaml /etc/brotli-envoy.yaml
RUN chmod go+r /etc/brotli-envoy.yaml
CMD ["/usr/local/bin/envoy", "-c", "/etc/brotli-envoy.yaml", "--service-cluster", "brotli"]
